download:
  output_path: data/dataset.csv

prepare:
  train_path: data/train.csv
  test_path: data/test.csv
  split:
    test_size: 0.2
    random_state: 42
  one_hot_encoding:
    columns:
    - sex
    - island
    encoder_path: models/encoder.pkl

train:
  model_path: models/model.pkl
  mlflow:
    experiment_name: penguin_classification
    model_name: PenguinsClassifier
  model:
    n_estimators: 50
    max_depth: 5
    min_samples_split: 2
    min_samples_leaf: 1
    bootstrap: true
    random_state: 42
