[data]
path = "data/training"
format = "csv"
validation_split = 0.2

[model]
type = "random_forest"
n_estimators = 100
max_depth = 10
random_state = 42

[training]
batch_size = 64
epochs = 10
learning_rate = 0.01
early_stopping = true
