stages:
  download_data:
    cmd: python download_data.py
    deps:
    - download_data.py
    - params.yaml
    outs:
    - data/dataset.csv
  train_model:
    cmd: python train_model.py
    params:
    - train.test_size
    - train.random_state
    - train.max_depth
    deps:
    - data/dataset.csv
    - params.yaml
    - train_model.py
    outs:
    - models/model.pkl
    metrics:
    - metrics.json:
        cache: false
